### ISSUE TITLE
Complementary Reimagined will add procedurally generated skies to the shader itself

### ISSUE THREAD

**Issue by MenacingPerson** [ZtereoHYPE/nicer-skies#12]
What happens to this mod's compat then?

**Comment by ZtereoHYPE** [comment]
Probably nothing, possibly the nebulas will stop being visible with the shaders turnd on.

**Comment by MenacingPerson** [comment]
Would it be possible to turn the cr skies off if nicer skies is installed?

**Comment by ZtereoHYPE** [comment]
Nicer skies has no control whatsoever over the shader code being loaded and what it does. If complementary will provide an option to show the vanilla sky, then probably yes, else no. That's fully up to them, and if you want to know you can ask them. I would recommend asking in a discord server or such, as the issue tracker is usually used to report issues. (I don't mind though :) )
