### ISSUE TITLE
End Sky Upgrade

### ISSUE THREAD

**Issue by JosephG1thub** [ZtereoHYPE/nicer-skies#19]
Hello, I have a good idea for your project, it would be great if there were galaxies, planets, etc., in the sky of the Final dimension, but above all, a black hole, it could be something similar to the one in the "Super Duper Vanilla" shader but more impotent and similar to that of the Interstellar movie, where everything is combined with an immersive background as if it were distorting space, that would be wonderful.

**Comment by ZtereoHYPE** [comment]
That would look cool, but I feel like having a static image of it would break the effect quite a bit. I will experiment with it when i have more free time and let you know

**Comment by ZtereoHYPE** [comment]
due to lack of time I won't be expanding the mod much further
