### ISSUE TITLE
Incompatibility with Distant Horizons 2.0

### ISSUE THREAD

**Issue by V-lpen** [ZtereoHYPE/nicer-skies#26]
Using [Distant Horizons](https://www.curseforge.com/minecraft/mc-mods/distant-horizons) 2.0 with Nicer skies causes the LODs to render black. 

Steps to reproduce: 
Use Distant Horizons + Nicer Skies on latest versions. 
All LODs will be black, until Nicer Skies is removed.

**Comment by ZtereoHYPE** [comment]
![image](https://github.com/ZtereoHYPE/nicer-skies/assets/57519662/20a2de80-e60d-42d1-85fe-6a70b3e8d256)
What's your setup?
I have a feeling this is gonna be a fun one to debug...

**Comment by ZtereoHYPE** [comment]
oh wait nevermind, joining a world with the nebulas on causes it to not work, but toggleing it while in doesn't

**Comment by ZtereoHYPE** [comment]
Should be fixed as of the latest commit, still gonna leave this issue open and close it when the release is out

**Comment by ZtereoHYPE** [comment]
It's out! sorry for the delay

https://modrinth.com/mod/nicer-skies/version/1.3.1+1.20.4

**Comment by V-lpen** [comment]
Any chance you could backport it to 1.20.1? :D DH only goes up to 1.20.2 but my modpack that I had this error on was .1

**Comment by ZtereoHYPE** [comment]
oh this is very silly, sorry for coupling it with the update. I'm gonna take a look
