### ISSUE TITLE
Not an issue, but rather a compatability!

### ISSUE THREAD

**Issue by Icilory** [ZtereoHYPE/nicer-skies#28]
You guys would probably find all the ins and outs, though from what I could tell and show from below; Botania's Garden of Glass skybox plays super well with your Nicer Skies. All the stars of the Garden of Glass twinkle; all of em'! Felt magical watching the entire thing. The layering is your nebulas in the back with Botania's skybox in the front.
I couldn't find a way to comment this somewhere else, so apologies on putting it here. I felt I had to bring it up because of how great it looked!

Daytime:
![2024-06-12_03 51 58](https://github.com/ZtereoHYPE/nicer-skies/assets/172494941/afa86566-85e2-4ca5-a876-70ae0271cd5f)
![2024-06-12_04 19 02](https://github.com/ZtereoHYPE/nicer-skies/assets/172494941/3400840e-5849-4042-8511-14642a699fa9)

Nighttime:
![2024-06-12_04 06 13](https://github.com/ZtereoHYPE/nicer-skies/assets/172494941/f85dc2be-1de4-4398-9cb4-a250fa1145f7)
![2024-06-12_04 11 17](https://github.com/ZtereoHYPE/nicer-skies/assets/172494941/433445d3-0775-4999-809a-19dfd927146b)
![2024-06-12_04 12 30](https://github.com/ZtereoHYPE/nicer-skies/assets/172494941/4f3e4a89-966c-4929-87f5-8c989f0d595f)

**Comment by ZtereoHYPE** [comment]
Aw, that does look great! Thanks for the nice comment!  :D

**Comment by ZtereoHYPE** [comment]
Might add that to the banner next update cycle
