### ISSUE TITLE
Weird horizontal divide with modpack

### ISSUE THREAD

**Issue by ZtereoHYPE** [ZtereoHYPE/nicer-skies#3]
Apparently disabling sky fixes these issues.
https://mclo.gs/abvmn7h for mod list

still have to gather more information

**Comment by ZtereoHYPE** [comment]
![image](https://user-images.githubusercontent.com/57519662/207983092-39a8d8a0-f78b-4e4e-9add-ded9d02f25c9.png)
![image](https://user-images.githubusercontent.com/57519662/207983100-602a7b69-dc2f-4a39-b2cc-a6d54783a91b.png)
here are examples

**Comment by ZtereoHYPE** [comment]
I don't seem to be able to reproduce this, the skybox blending usually looks smooth. If anyone has this issue please respond to this. Turning off the sky is a temporary fix.

**Comment by Scarlaid** [comment]
what sky are you using though?

I'm currently using **FAT's Sky** with 
- FabricSkyboxes latest version (v0.6.1+mc1.19.2)
- FabricSkyBoxes Interop latest version (v1.1.3+mc1.19.2-build.25)
- Nicer Skyies latest version (v0.1.0)
- MCPPPP+ latest version (v0.7.3)

The sky is not converted using MCPPPP+ application, rather converted using Interop
My modlist: [latest.log](https://github.com/ZtereoHYPE/nicer-skies/files/10253158/latest.log)


Not having any skybox issue like your given picture
![2022-12-18_10 43 10](https://user-images.githubusercontent.com/90851437/208280381-e5cbd2f0-ca18-4d92-8ac1-da6dc37d6263.png)
![2022-12-18_10 48 22](https://user-images.githubusercontent.com/90851437/208280383-7f2dba21-2ba9-4cf2-bb9d-2486601989a5.png)

**Comment by ZtereoHYPE** [comment]
Apparently no custom skybox was being used, the person had just customised something about the vanilla sky that caused the smooth transition between the different parts of it to disappear. If anything similar ever happens again I'll look into it. Else, I'll close this issue.

**Comment by ZtereoHYPE** [comment]
Will close as it hasn't manifested itself ever since.
