### ISSUE TITLE
Compatibility with Custom Stars Mod

### ISSUE THREAD

**Issue by Turioyt** [ZtereoHYPE/nicer-skies#5]
I think it would be cool if I could use these two mods alongside eachother. Currently, only the Nicer Skies sky shows. But it would be ideal imo to have the stars from the custom stars mod render over it. So I would have the amazing looking nebulas from this mod with the customization of the stars, night sky and moon from the Custom Stars Mod. I'm not sure if this is possible or not but if not I'll probably just have to make a choice between the two.
P.S. I've also made an issue on the Custom Stars github similar to this one.

Curseforge link: https://www.curseforge.com/minecraft/mc-mods/custom-stars
Github: https://github.com/b3spectacled/custom-stars

**Comment by ZtereoHYPE** [comment]
Taking a look to see what I can do to add compatibility. Just to be sure, does it not work if you toggle off twinkling stars?

Edit: confirmed it doesn't and patching it so that it does ;)

**Comment by ZtereoHYPE** [comment]
![image](https://user-images.githubusercontent.com/57519662/210117215-e1635716-e761-4d7e-ac70-01375f36b0dd.png)
almost ready

**Comment by ZtereoHYPE** [comment]
Fixed with latest release!
