### ISSUE TITLE
(Idea) Daytime sky improvement

### ISSUE THREAD

**Issue by JosephG1thub** [ZtereoHYPE/nicer-skies#7]
I love this mod, especially because I have a lot of incompatibilities with fabric-skyboxes and this has been my solution, I just want to propose that clouds or something could be added to it for the daytime sky, this would improve the mod a lot, I hope you will consider adding this idea, goodbye

"I speak Spanish, sorry if there is something misspelled"

**Comment by ZtereoHYPE** [comment]
That's a good idea I experimented with in the past already, but the results were quite underwhelming and looked quite bad. I might try giving it a shot though. (BTW there's a "nebulas during the day" option if you wanna try that ;)

**Comment by JosephG1thub** [comment]
Hello, I had already tried it, and the truth is very good, I have combined it with the "clear skys" mod to adjust the color of the sky with respect to the fog in the game and remove the void below sea level, even so there is the feeling that something is missing (the clouds) since the night is very beautiful and the day lacks that touch for the sky; I'm not a programmer, let alone a texturizer, but maybe you could be inspired by texture packs like "fancy skies" among others. Other than that, your mod is great and I plan to use it in future versions, bye

**Comment by ZtereoHYPE** [comment]
The issue can be left open in case i ever have an idea on making it look good :) 

Thanks for the feedback!

**Comment by JosephG1thub** [comment]
ok! ;)
