### ISSUE TITLE
1.20.1 support

### ISSUE THREAD

**Issue by MenacingPerson** [ZtereoHYPE/nicer-skies#8]
Only the fabric mod json needs to be updated to support 1.20.1

Everything else works as is

**Comment by MenacingPerson** [comment]
It would be ideal to also keep 1.20 support as it is the same code

**Comment by ZtereoHYPE** [comment]
> Only the fabric mod json needs to be updated to support 1.20.1

did you test?

also, sorry for this, i have been very busy with exams lately

**Comment by ZtereoHYPE** [comment]
could confirm it works

**Comment by MenacingPerson** [comment]
The only difference between the two versions is some realms and server connections stuff basically
