### ISSUE TITLE
Sun both during days and nights

### ISSUE THREAD

**Issue by Soulfate24** [ZtereoHYPE/nicer-skies#9]
I'm using Minecraft 1.20.1 (with Quilt) and Nicer Skies shows Sun both during days and nights (there is no moon). No problem when I'm using shader's integrated Sun/Moon. Do you have any idea of what is causing this issue? Ty

**Comment by ZtereoHYPE** [comment]
Apologies for the delayed response. What shaderpack are you using that is causing the issue?

**Comment by Soulfate24** [comment]
No problem and of course I should have precised it is with Complementary shader (not the reimagined one). So today I've done some research about vanilla skybox and I was totally creeped out about how vanilla skybox is managing astral entities.
There is no issue with Nicer Skies because my issue was about the "Sun/Moon path rotation" option. I don't know exactly how it works but it rotates the whole skymap, so finally letting me view sun during night and day. The moon hasn't been replaced by sun (I've realized later that even moon was visible both during night and day).

**Comment by ZtereoHYPE** [comment]
![image](https://github.com/ZtereoHYPE/nicer-skies/assets/57519662/74a3db41-c352-4d98-a2af-e9c0ad605250)
I can't seem to be able to reproduce. What are your shaderpack settings? I disabled shader sun and moon and enabled vanilla sun/moon/overlay

**Comment by ZtereoHYPE** [comment]
I just realized, rereading the comment above, that this has nothing to do with my mod. how silly of me, should've read better
